import {
  inflacionAnual,
  tasaInteres,
  spread,
  frenoAcelerador,
  pibInflacion,
} from "./inflacion";
import {
  crecimientoPib,
  pibTotal,
  poblacionPib,
  deudaPublica,
  pibComercio,
} from "./pib";
import {
  desempleo,
  subempleo,
  tgpToDual,
  brechaLaboral,
} from "./empleo";
import {
  balanzaComercial,
  apertura,
  matrizExportaciones,
  matrizImportaciones,
  participacionExportaciones,
  participacionImportaciones,
  productosTradicionales,
} from "./comercio";
import { comparativoUzb, comparativoCog, comparativoPrt, comparativoGha } from "./comparativo";
import {
  inflacionHistorica,
  pibHistorico,
  pibPerCapitaHistorico,
  desempleoHistorico,
  salarioMinimoHistorico,
  salarioMinimoVariacion,
  comercioHistorico,
  importacionesHistorica,
  poblacionHistorica,
} from "./historico";
import {
  poblacionCrecimiento,
  esperanzaVida,
  giniEvolucion,
} from "./demografia";
import {
  trmHistorica,
  reservasInternacionales,
  cuentaCorrientePib,
  deudaExternaPib,
  passThroughTrmInflacion,
} from "./externo";
import {
  pres2026ComposicionVotos,
  pres2026ParticipacionHistorico,
  pres2026VotosCandidato,
  pres2026MapaDeptoGanador,
  presIdeologia2026,
  presIdeologia2022,
  pres2022_1vComposicionVotos,
  pres2022_1vVotosCandidato,
  pres2022_1vMapaDeptoGanador,
  pres2022_2vComposicionVotos,
  pres2022_2vVotosCandidato,
  pres2022_2vMapaDeptoGanador,
  pres2022_2vMovimientoNacional,
  pres2022_2vDeltaValidosDepto,
  pres2022_2vDeltaPetroDepto,
  pres2022_2vConsolidacionAntiPetro,
  pres2022_2vMapaVariacionCandidato,
  pres2026_2vComposicionVotos,
  pres2026_2vVotosCandidato,
  pres2026_2vMapaDeptoGanador,
  pres2026_2vMovimientoNacional,
  pres2026_2vDeltaValidosDepto,
  pres2026_2vDeltaGanadorDepto,
  pres2026_2vConsolidacionBloque,
  pres2026_2vMapaVariacionCandidato,
  pres2026_2vMapaMunicipio,
  pres2026_2vDistribucionMargenes,
  pres2026_2vMapaDesafeccion,
  pres2026MapaVariacionTendencia,
  pres2026_2vPronosticoComposicion,
  pres2026_2vPronosticoMargenDepto,
  pres2026_2vPronosticoMapaGanador,
  pres2026_2vPronosticoMontecarlo,
  pres2026_2vDiferenciaVariacion,
} from "./elecciones-presidenciales";
import {
  presComparativoDesplazamientoIdeologico,
  pres2026_2vTransferenciaEndosos,
  pres2026_2vVotoNoPositivo,
  pres2026_2vAporteNetoMargen,
  pres2026_2vRetrocesoIzquierda,
  pres2026_2vVotoExterior,
  pres2026_2vPolarizacionTerritorial,
} from "./analisis-electoral";
import type { ChartDef } from "./types";

// Charts del Observatorio: registro explícito → TypeScript detecta ids duplicados.
const BASE_DEFS = {
  [inflacionAnual.id]: inflacionAnual,
  [tasaInteres.id]: tasaInteres,
  [spread.id]: spread,
  [frenoAcelerador.id]: frenoAcelerador,
  [pibInflacion.id]: pibInflacion,
  [crecimientoPib.id]: crecimientoPib,
  [pibTotal.id]: pibTotal,
  [poblacionPib.id]: poblacionPib,
  [deudaPublica.id]: deudaPublica,
  [pibComercio.id]: pibComercio,
  [desempleo.id]: desempleo,
  [subempleo.id]: subempleo,
  [tgpToDual.id]: tgpToDual,
  [brechaLaboral.id]: brechaLaboral,
  [balanzaComercial.id]: balanzaComercial,
  [apertura.id]: apertura,
  [matrizExportaciones.id]: matrizExportaciones,
  [matrizImportaciones.id]: matrizImportaciones,
  [participacionExportaciones.id]: participacionExportaciones,
  [participacionImportaciones.id]: participacionImportaciones,
  [productosTradicionales.id]: productosTradicionales,
  [inflacionHistorica.id]: inflacionHistorica,
  [pibHistorico.id]: pibHistorico,
  [pibPerCapitaHistorico.id]: pibPerCapitaHistorico,
  [desempleoHistorico.id]: desempleoHistorico,
  [salarioMinimoHistorico.id]: salarioMinimoHistorico,
  [salarioMinimoVariacion.id]: salarioMinimoVariacion,
  [comercioHistorico.id]: comercioHistorico,
  [importacionesHistorica.id]: importacionesHistorica,
  [poblacionHistorica.id]: poblacionHistorica,
  [poblacionCrecimiento.id]: poblacionCrecimiento,
  [esperanzaVida.id]: esperanzaVida,
  [giniEvolucion.id]: giniEvolucion,
  [trmHistorica.id]: trmHistorica,
  [reservasInternacionales.id]: reservasInternacionales,
  [cuentaCorrientePib.id]: cuentaCorrientePib,
  [deudaExternaPib.id]: deudaExternaPib,
  [passThroughTrmInflacion.id]: passThroughTrmInflacion,
  [pres2026ComposicionVotos.id]: pres2026ComposicionVotos,
  [pres2026ParticipacionHistorico.id]: pres2026ParticipacionHistorico,
  [pres2026VotosCandidato.id]: pres2026VotosCandidato,
  [pres2026MapaDeptoGanador.id]: pres2026MapaDeptoGanador,
  [presIdeologia2026.id]: presIdeologia2026,
  [presIdeologia2022.id]: presIdeologia2022,
  [pres2022_1vComposicionVotos.id]: pres2022_1vComposicionVotos,
  [pres2022_1vVotosCandidato.id]: pres2022_1vVotosCandidato,
  [pres2022_1vMapaDeptoGanador.id]: pres2022_1vMapaDeptoGanador,
  [pres2022_2vComposicionVotos.id]: pres2022_2vComposicionVotos,
  [pres2022_2vVotosCandidato.id]: pres2022_2vVotosCandidato,
  [pres2022_2vMapaDeptoGanador.id]: pres2022_2vMapaDeptoGanador,
  [pres2022_2vMovimientoNacional.id]: pres2022_2vMovimientoNacional,
  [pres2022_2vDeltaValidosDepto.id]: pres2022_2vDeltaValidosDepto,
  [pres2022_2vDeltaPetroDepto.id]: pres2022_2vDeltaPetroDepto,
  [pres2022_2vConsolidacionAntiPetro.id]: pres2022_2vConsolidacionAntiPetro,
  [pres2022_2vMapaVariacionCandidato.id]: pres2022_2vMapaVariacionCandidato,
  [pres2026_2vComposicionVotos.id]: pres2026_2vComposicionVotos,
  [pres2026_2vVotosCandidato.id]: pres2026_2vVotosCandidato,
  [pres2026_2vMapaDeptoGanador.id]: pres2026_2vMapaDeptoGanador,
  [pres2026_2vMovimientoNacional.id]: pres2026_2vMovimientoNacional,
  [pres2026_2vDeltaValidosDepto.id]: pres2026_2vDeltaValidosDepto,
  [pres2026_2vDeltaGanadorDepto.id]: pres2026_2vDeltaGanadorDepto,
  [pres2026_2vConsolidacionBloque.id]: pres2026_2vConsolidacionBloque,
  [pres2026_2vMapaVariacionCandidato.id]: pres2026_2vMapaVariacionCandidato,
  [pres2026_2vMapaMunicipio.id]: pres2026_2vMapaMunicipio,
  [pres2026_2vDistribucionMargenes.id]: pres2026_2vDistribucionMargenes,
  [pres2026_2vMapaDesafeccion.id]: pres2026_2vMapaDesafeccion,
  [pres2026MapaVariacionTendencia.id]: pres2026MapaVariacionTendencia,
  [pres2026_2vPronosticoComposicion.id]: pres2026_2vPronosticoComposicion,
  [pres2026_2vPronosticoMargenDepto.id]: pres2026_2vPronosticoMargenDepto,
  [pres2026_2vPronosticoMapaGanador.id]: pres2026_2vPronosticoMapaGanador,
  [pres2026_2vPronosticoMontecarlo.id]: pres2026_2vPronosticoMontecarlo,
  [pres2026_2vDiferenciaVariacion.id]: pres2026_2vDiferenciaVariacion,
  [presComparativoDesplazamientoIdeologico.id]: presComparativoDesplazamientoIdeologico,
  [pres2026_2vRetrocesoIzquierda.id]: pres2026_2vRetrocesoIzquierda,
  [pres2026_2vVotoExterior.id]: pres2026_2vVotoExterior,
  [pres2026_2vPolarizacionTerritorial.id]: pres2026_2vPolarizacionTerritorial,
  [pres2026_2vAporteNetoMargen.id]: pres2026_2vAporteNetoMargen,
  [pres2026_2vTransferenciaEndosos.id]: pres2026_2vTransferenciaEndosos,
  [pres2026_2vVotoNoPositivo.id]: pres2026_2vVotoNoPositivo,
} as const satisfies Record<string, ChartDef>;

// Sets comparativos (Colombia vs rival): generados por factory, ids únicos por
// construcción (clave de rival × indicador). Se fusionan en el registro de lookup.
const COMPARATIVO_DEFS: ChartDef[] = [...comparativoUzb, ...comparativoCog, ...comparativoPrt, ...comparativoGha];

const CHART_DEFS: Record<string, ChartDef> = {
  ...BASE_DEFS,
  ...Object.fromEntries(COMPARATIVO_DEFS.map((d) => [d.id, d])),
};

/** Ids con autocompletado para los charts del Observatorio; acepta también los `cmp-*`. */
export type ChartId = Extract<keyof typeof BASE_DEFS, string> | (string & {});

export const getChartDef = (id: string): ChartDef | undefined => CHART_DEFS[id];

export type { ChartDef };
