import {
  inflacionAnual,
  tasaInteres,
  spread,
  frenoAcelerador,
  pibInflacion,
} from "./inflacion";
import {
  crecimientoPib,
  pibTotal,
  poblacionPib,
  deudaPublica,
  pibComercio,
} from "./pib";
import {
  desempleo,
  subempleo,
  tgpToDual,
  brechaLaboral,
} from "./empleo";
import {
  balanzaComercial,
  apertura,
  matrizExportaciones,
  matrizImportaciones,
  participacionExportaciones,
  participacionImportaciones,
  productosTradicionales,
} from "./comercio";
import {
  inflacionHistorica,
  pibHistorico,
  pibPerCapitaHistorico,
  desempleoHistorico,
  salarioMinimoHistorico,
  salarioMinimoVariacion,
  comercioHistorico,
  importacionesHistorica,
  poblacionHistorica,
} from "./historico";
import {
  poblacionCrecimiento,
  esperanzaVida,
  giniEvolucion,
} from "./demografia";
import {
  trmHistorica,
  reservasInternacionales,
  cuentaCorrientePib,
  deudaExternaPib,
  passThroughTrmInflacion,
} from "./externo";
import {
  pres2026ComposicionVotos,
  pres2026ParticipacionHistorico,
  pres2026VotosCandidato,
  pres2026MapaDeptoGanador,
  presIdeologia2026,
  presIdeologia2022,
  pres2022_1vComposicionVotos,
  pres2022_1vVotosCandidato,
  pres2022_1vMapaDeptoGanador,
  pres2022_2vComposicionVotos,
  pres2022_2vVotosCandidato,
  pres2022_2vMapaDeptoGanador,
  pres2022_2vMovimientoNacional,
  pres2022_2vDeltaValidosDepto,
  pres2022_2vDeltaPetroDepto,
  pres2022_2vConsolidacionAntiPetro,
  pres2022_2vMapaVariacionCandidato,
  pres2026MapaVariacionTendencia,
  pres2026_2vPronosticoComposicion,
  pres2026_2vPronosticoMargenDepto,
  pres2026_2vPronosticoMapaGanador,
  pres2026_2vPronosticoMontecarlo,
} from "./elecciones-presidenciales";
import type { ChartDef } from "./types";

export const CHART_DEFS = {
  [inflacionAnual.id]: inflacionAnual,
  [tasaInteres.id]: tasaInteres,
  [spread.id]: spread,
  [frenoAcelerador.id]: frenoAcelerador,
  [pibInflacion.id]: pibInflacion,
  [crecimientoPib.id]: crecimientoPib,
  [pibTotal.id]: pibTotal,
  [poblacionPib.id]: poblacionPib,
  [deudaPublica.id]: deudaPublica,
  [pibComercio.id]: pibComercio,
  [desempleo.id]: desempleo,
  [subempleo.id]: subempleo,
  [tgpToDual.id]: tgpToDual,
  [brechaLaboral.id]: brechaLaboral,
  [balanzaComercial.id]: balanzaComercial,
  [apertura.id]: apertura,
  [matrizExportaciones.id]: matrizExportaciones,
  [matrizImportaciones.id]: matrizImportaciones,
  [participacionExportaciones.id]: participacionExportaciones,
  [participacionImportaciones.id]: participacionImportaciones,
  [productosTradicionales.id]: productosTradicionales,
  [inflacionHistorica.id]: inflacionHistorica,
  [pibHistorico.id]: pibHistorico,
  [pibPerCapitaHistorico.id]: pibPerCapitaHistorico,
  [desempleoHistorico.id]: desempleoHistorico,
  [salarioMinimoHistorico.id]: salarioMinimoHistorico,
  [salarioMinimoVariacion.id]: salarioMinimoVariacion,
  [comercioHistorico.id]: comercioHistorico,
  [importacionesHistorica.id]: importacionesHistorica,
  [poblacionHistorica.id]: poblacionHistorica,
  [poblacionCrecimiento.id]: poblacionCrecimiento,
  [esperanzaVida.id]: esperanzaVida,
  [giniEvolucion.id]: giniEvolucion,
  [trmHistorica.id]: trmHistorica,
  [reservasInternacionales.id]: reservasInternacionales,
  [cuentaCorrientePib.id]: cuentaCorrientePib,
  [deudaExternaPib.id]: deudaExternaPib,
  [passThroughTrmInflacion.id]: passThroughTrmInflacion,
  [pres2026ComposicionVotos.id]: pres2026ComposicionVotos,
  [pres2026ParticipacionHistorico.id]: pres2026ParticipacionHistorico,
  [pres2026VotosCandidato.id]: pres2026VotosCandidato,
  [pres2026MapaDeptoGanador.id]: pres2026MapaDeptoGanador,
  [presIdeologia2026.id]: presIdeologia2026,
  [presIdeologia2022.id]: presIdeologia2022,
  [pres2022_1vComposicionVotos.id]: pres2022_1vComposicionVotos,
  [pres2022_1vVotosCandidato.id]: pres2022_1vVotosCandidato,
  [pres2022_1vMapaDeptoGanador.id]: pres2022_1vMapaDeptoGanador,
  [pres2022_2vComposicionVotos.id]: pres2022_2vComposicionVotos,
  [pres2022_2vVotosCandidato.id]: pres2022_2vVotosCandidato,
  [pres2022_2vMapaDeptoGanador.id]: pres2022_2vMapaDeptoGanador,
  [pres2022_2vMovimientoNacional.id]: pres2022_2vMovimientoNacional,
  [pres2022_2vDeltaValidosDepto.id]: pres2022_2vDeltaValidosDepto,
  [pres2022_2vDeltaPetroDepto.id]: pres2022_2vDeltaPetroDepto,
  [pres2022_2vConsolidacionAntiPetro.id]: pres2022_2vConsolidacionAntiPetro,
  [pres2022_2vMapaVariacionCandidato.id]: pres2022_2vMapaVariacionCandidato,
  [pres2026MapaVariacionTendencia.id]: pres2026MapaVariacionTendencia,
  [pres2026_2vPronosticoComposicion.id]: pres2026_2vPronosticoComposicion,
  [pres2026_2vPronosticoMargenDepto.id]: pres2026_2vPronosticoMargenDepto,
  [pres2026_2vPronosticoMapaGanador.id]: pres2026_2vPronosticoMapaGanador,
  [pres2026_2vPronosticoMontecarlo.id]: pres2026_2vPronosticoMontecarlo,
} as const satisfies Record<string, ChartDef>;

export type ChartId = Extract<keyof typeof CHART_DEFS, string>;

export const getChartDef = (id: string): ChartDef | undefined =>
  (CHART_DEFS as Record<string, ChartDef>)[id];

export type { ChartDef };
